In [1]:
import os
from PIL import Image
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

In [ ]:
df = pd.read_csv("/Users/harshit/Downloads/final_df.csv")
image_dir = "/Users/harshit/Downloads/"
sample_size = 5000  # Number of images to process

/var/folders/p4/clcxcgh13kq1q94gkwwxk9ch0000gn/T/ipykernel_1433/2864794929.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/harshit/Downloads/final_df.csv")


In [ ]:
def load_image(image_path):
    img = Image.open(os.path.join(image_dir, image_path))
    img = img.resize((224, 224))  # Resize image to match ResNet50 input size
    img = img.convert('RGB')  # Convert image to RGB if it's in grayscale or other formats
    return img

In [ ]:
base_model = ResNet50(weights="imagenet", include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

In [ ]:
def extract_features(image_path):
    img = load_image(image_path)
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)  # Create batch axis
    img_array = tf.keras.applications.resnet50.preprocess_input(img_array)  # Preprocess input
    features = base_model.predict(img_array)  # Extract features
    features = features.flatten()  # Flatten features
    return features

In [ ]:
image_paths = df["Path"].values[:sample_size]  # Select first 10,000 images
extracted_features = [extract_features(path) for path in image_paths]

1/1 [==============================] - 0s 47ms/step


In [ ]:
extracted_features

[array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.       , 0.       , 0.       , ..., 3.4201114, 0.       ,
        0.1906873], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.     , 0.14063, 0.     , ..., 0.     , 0.     , 0.     ],
       dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.       , 0.       , 0.       , ..., 0.       , 4.3573875,
        0.       ], dtype=float32),
 array([0.       , 0.       , 0.       , ..., 3.3169522, 0.       ,
        0.       ], dtype=float32),
 array([0.       , 0.       , 0.       , ..., 3.9172592, 0.       ,
        0.       ], dtype=float32),
 array([ 0.       ,  0.       ,  0.       , ..., 11.412643 ,  0.7222688,
         0.       ], dtype=float32),
 arra

In [ ]:
extracted_features[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
extracted_features[0][0]

0.0

In [ ]:
extracted_features[7][1]

0.14063

In [ ]:
extract = pd.DataFrame({'path': image_paths, 'features': extracted_features})

In [ ]:
extract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   path      10000 non-null  object
 1   features  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB


In [ ]:
extract

path  \
0       test/8770@N36/50731.jpg   
1      test/10082@N16/96454.jpg   
2     test/10082@N16/172136.jpg   
3     test/24607@N38/177707.jpg   
4     test/24607@N38/177708.jpg   
...                         ...   
9995   test/7942@N97/703695.jpg   
9996   test/7942@N97/703696.jpg   
9997  test/64066@N78/703697.jpg   
9998  test/64066@N78/703702.jpg   
9999  test/64066@N78/703703.jpg   

                                               features  
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.260445, 0.0,...  
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
...                                                 ...  
9995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
9996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
9997  [0.0, 1.5452662, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
9998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
9999  [0.0, 3.2544665, 0.0, 0.0, 0.0, 0.0, 1.813087,...  

[10000 rows x 2 columns]

In [ ]:
extract["features"]

0       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.260445, 0.0,...
1       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
                              ...                        
9995    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9996    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9997    [0.0, 1.5452662, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
9998    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9999    [0.0, 3.2544665, 0.0, 0.0, 0.0, 0.0, 1.813087,...
Name: features, Length: 10000, dtype: object

In [ ]:
extract.to_json('image_features.json')

In [ ]:
df = pd.read_csv("/Users/harshit/Downloads/final_m_df.csv")

In [ ]:
df

Category_encoded  Subcategory_encoded  Concept_encoded  \
0             6.422156             6.515767         6.500651   
1             6.562402             6.603636         6.572583   
2             6.428840             6.468631         6.355811   
3             6.562402             6.603636         6.282670   
4             6.562402             6.603636         6.282670   
...                ...                  ...              ...   
9995          6.422156             6.306170         6.343759   
9996          6.422156             6.306170         6.343759   
9997          6.376465             6.382948         6.835919   
9998          6.376465             6.382948         6.835919   
9999          6.376465             6.382948         6.835919   

                                         image_features  \
0                               [0. 0. 0. ... 0. 0. 0.]   
1                               [0. 0. 0. ... 0. 0. 0.]   
2     [0.        0.        0.        ... 3.4201114 0...   
3                               [0. 0. 0. ... 0. 0. 0.]   
4                               [0. 0. 0. ... 0. 0. 0.]   
...                                                 ...   
9995  [0.         0.         0.         ... 0.      ...   
9996  [0.        0.        0.        ... 5.1891365 0...   
9997  [0.        1.5452662 0.        ... 1.3739994 0...   
9998                            [0. 0. 0. ... 0. 0. 0.]   
9999  [0.        3.2544665 0.        ... 0.        0...   

                                             tag_vector  popularity_score  
0     [0.0, 0.014631420373916626, 0.0244596097618341...             11.18  
1                  [0.0, 0.0, 0.0, 0.08623579144477844]              6.74  
2     [0.03217782452702522, 0.2367417812347412, 0.0,...              5.45  
3     [0.13340169191360474, 0.037952471524477005, 0....              7.05  
4     [0.022980470210313797, 0.06730880588293076, 0....              5.43  
...                                                 ...               ...  
9995  [0.0, 0.0, 0.2529948353767395, 0.0622927136719...              6.95  
9996  [0.0, 0.5479055643081665, 0.0, 0.2525905668735...              5.70  
9997  [0.17933450639247894, 0.03311112895607948, 0.0...             12.95  
9998               [0.0, 0.0, 0.0, 0.03291860222816467]              3.66  
9999  [0.25104615092277527, 0.0, 0.18950018286705017...              6.39  

[10000 rows x 6 columns]

In [ ]:
df.drop('image_features', inplace=True,axis=1)

In [ ]:
df

Category_encoded  Subcategory_encoded  Concept_encoded  \
0             6.422156             6.515767         6.500651   
1             6.562402             6.603636         6.572583   
2             6.428840             6.468631         6.355811   
3             6.562402             6.603636         6.282670   
4             6.562402             6.603636         6.282670   
...                ...                  ...              ...   
9995          6.422156             6.306170         6.343759   
9996          6.422156             6.306170         6.343759   
9997          6.376465             6.382948         6.835919   
9998          6.376465             6.382948         6.835919   
9999          6.376465             6.382948         6.835919   

                                             tag_vector  popularity_score  
0     [0.0, 0.014631420373916626, 0.0244596097618341...             11.18  
1                  [0.0, 0.0, 0.0, 0.08623579144477844]              6.74  
2     [0.03217782452702522, 0.2367417812347412, 0.0,...              5.45  
3     [0.13340169191360474, 0.037952471524477005, 0....              7.05  
4     [0.022980470210313797, 0.06730880588293076, 0....              5.43  
...                                                 ...               ...  
9995  [0.0, 0.0, 0.2529948353767395, 0.0622927136719...              6.95  
9996  [0.0, 0.5479055643081665, 0.0, 0.2525905668735...              5.70  
9997  [0.17933450639247894, 0.03311112895607948, 0.0...             12.95  
9998               [0.0, 0.0, 0.0, 0.03291860222816467]              3.66  
9999  [0.25104615092277527, 0.0, 0.18950018286705017...              6.39  

[10000 rows x 5 columns]

In [ ]:
new_df = pd.merge(extract, df, left_index=True, right_index=True, how='inner')

In [ ]:
new_df

path  \
0       test/8770@N36/50731.jpg   
1      test/10082@N16/96454.jpg   
2     test/10082@N16/172136.jpg   
3     test/24607@N38/177707.jpg   
4     test/24607@N38/177708.jpg   
...                         ...   
9995   test/7942@N97/703695.jpg   
9996   test/7942@N97/703696.jpg   
9997  test/64066@N78/703697.jpg   
9998  test/64066@N78/703702.jpg   
9999  test/64066@N78/703703.jpg   

                                               features  Category_encoded  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.260445, 0.0,...          6.422156   
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.428840   
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
...                                                 ...               ...   
9995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9997  [0.0, 1.5452662, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...          6.376465   
9998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.376465   
9999  [0.0, 3.2544665, 0.0, 0.0, 0.0, 0.0, 1.813087,...          6.376465   

      Subcategory_encoded  Concept_encoded  \
0                6.515767         6.500651   
1                6.603636         6.572583   
2                6.468631         6.355811   
3                6.603636         6.282670   
4                6.603636         6.282670   
...                   ...              ...   
9995             6.306170         6.343759   
9996             6.306170         6.343759   
9997             6.382948         6.835919   
9998             6.382948         6.835919   
9999             6.382948         6.835919   

                                             tag_vector  popularity_score  
0     [0.0, 0.014631420373916626, 0.0244596097618341...             11.18  
1                  [0.0, 0.0, 0.0, 0.08623579144477844]              6.74  
2     [0.03217782452702522, 0.2367417812347412, 0.0,...              5.45  
3     [0.13340169191360474, 0.037952471524477005, 0....              7.05  
4     [0.022980470210313797, 0.06730880588293076, 0....              5.43  
...                                                 ...               ...  
9995  [0.0, 0.0, 0.2529948353767395, 0.0622927136719...              6.95  
9996  [0.0, 0.5479055643081665, 0.0, 0.2525905668735...              5.70  
9997  [0.17933450639247894, 0.03311112895607948, 0.0...             12.95  
9998               [0.0, 0.0, 0.0, 0.03291860222816467]              3.66  
9999  [0.25104615092277527, 0.0, 0.18950018286705017...              6.39  

[10000 rows x 7 columns]

In [ ]:
new_df.drop('path', axis=1, inplace=True)

In [ ]:
new_df

features  Category_encoded  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.260445, 0.0,...          6.422156   
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.428840   
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
...                                                 ...               ...   
9995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9997  [0.0, 1.5452662, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...          6.376465   
9998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.376465   
9999  [0.0, 3.2544665, 0.0, 0.0, 0.0, 0.0, 1.813087,...          6.376465   

      Subcategory_encoded  Concept_encoded  \
0                6.515767         6.500651   
1                6.603636         6.572583   
2                6.468631         6.355811   
3                6.603636         6.282670   
4                6.603636         6.282670   
...                   ...              ...   
9995             6.306170         6.343759   
9996             6.306170         6.343759   
9997             6.382948         6.835919   
9998             6.382948         6.835919   
9999             6.382948         6.835919   

                                             tag_vector  popularity_score  
0     [0.0, 0.014631420373916626, 0.0244596097618341...             11.18  
1                  [0.0, 0.0, 0.0, 0.08623579144477844]              6.74  
2     [0.03217782452702522, 0.2367417812347412, 0.0,...              5.45  
3     [0.13340169191360474, 0.037952471524477005, 0....              7.05  
4     [0.022980470210313797, 0.06730880588293076, 0....              5.43  
...                                                 ...               ...  
9995  [0.0, 0.0, 0.2529948353767395, 0.0622927136719...              6.95  
9996  [0.0, 0.5479055643081665, 0.0, 0.2525905668735...              5.70  
9997  [0.17933450639247894, 0.03311112895607948, 0.0...             12.95  
9998               [0.0, 0.0, 0.0, 0.03291860222816467]              3.66  
9999  [0.25104615092277527, 0.0, 0.18950018286705017...              6.39  

[10000 rows x 6 columns]

In [ ]:
features_array = np.array(new_df['features'].tolist())

In [ ]:
from sklearn.decomposition import PCA
pca_features = PCA(n_components=2)  # Specify the number of components you want to reduce to
features_pca_result = pca_features.fit_transform(features_array)

In [ ]:
new_df['tag_vector'] = new_df['tag_vector'].str.replace('\x00', '')

In [ ]:
new_df['tag_vector'] = new_df['tag_vector'].apply(lambda x: np.array(eval(x), dtype=float).tolist())

In [ ]:
tag_vector_array = np.array(new_df['tag_vector'].tolist())

In [ ]:
pca_tag_vector = PCA(n_components=2)  # Specify the number of components you want to reduce to
tag_vector_pca_result = pca_tag_vector.fit_transform(tag_vector_array)

In [ ]:
new_df['features_PCA1'] = features_pca_result[:, 0]
new_df['features_PCA2'] = features_pca_result[:, 1]
new_df['tag_vector_PCA'] = tag_vector_pca_result.flatten()

In [ ]:
new_df

features  Category_encoded  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.260445, 0.0,...          6.422156   
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.428840   
3     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
4     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.562402   
...                                                 ...               ...   
9995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.422156   
9997  [0.0, 1.5452662, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...          6.376465   
9998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...          6.376465   
9999  [0.0, 3.2544665, 0.0, 0.0, 0.0, 0.0, 1.813087,...          6.376465   

      Subcategory_encoded  Concept_encoded  \
0                6.515767         6.500651   
1                6.603636         6.572583   
2                6.468631         6.355811   
3                6.603636         6.282670   
4                6.603636         6.282670   
...                   ...              ...   
9995             6.306170         6.343759   
9996             6.306170         6.343759   
9997             6.382948         6.835919   
9998             6.382948         6.835919   
9999             6.382948         6.835919   

                                             tag_vector  popularity_score  \
0     [0.0, 0.014631420373916626, 0.0244596097618341...             11.18   
1                  [0.0, 0.0, 0.0, 0.08623579144477844]              6.74   
2     [0.03217782452702522, 0.2367417812347412, 0.0,...              5.45   
3     [0.13340169191360474, 0.037952471524477005, 0....              7.05   
4     [0.022980470210313797, 0.06730880588293076, 0....              5.43   
...                                                 ...               ...   
9995  [0.0, 0.0, 0.2529948353767395, 0.0622927136719...              6.95   
9996  [0.0, 0.5479055643081665, 0.0, 0.2525905668735...              5.70   
9997  [0.17933450639247894, 0.03311112895607948, 0.0...             12.95   
9998               [0.0, 0.0, 0.0, 0.03291860222816467]              3.66   
9999  [0.25104615092277527, 0.0, 0.18950018286705017...              6.39   

      features_PCA1  features_PCA2  
0         21.694414     -17.770844  
1        -13.963053     -27.770741  
2          7.634014      19.904741  
3        -96.406258      48.497921  
4       -102.098701      39.462158  
...             ...            ...  
9995     -75.129333      29.828913  
9996     -81.266747      29.290861  
9997     -77.063103      65.000504  
9998     -89.782471      16.204468  
9999     -70.883583      10.645839  

[10000 rows x 8 columns]